plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mokafeefah.clicker'
    compileSdk 34

    defaultConfig {
        applicationId 'com.mokafeefah.clicker'
        minSdk 24
        targetSdk 34
        versionCode 33
        versionName '1.13.0'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
}
